apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
  namespace: default
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: volodymyr.skliar@nure.ua
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      dns01:
        clouddns:
           project: devops-259416
           serviceAccountSecretRef:
             name: k8s-service-account
             key: key.json
---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: hipster-cert
  namespace: default
spec:
  secretName: hipster-cert-tls
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  dnsZones:
  - sxvova
  dnsNames:
  - hipster-shop.sxvova.opensource-ukraine.org
